apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrop-notebook-deployment
  labels:
    kueue.x-k8s.io/queue-name: eidf018ns-user-queue
    eidf/user: s2908448-aspp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mrop-jupyter
  template:
    metadata:
      labels:
        app: mrop-jupyter
        eidf/user: s2908448-aspp
    spec:
      securityContext:
        fsGroup: 3607
      containers:
      - name: jupyter
        stdin: true
        image: davidleeb24/mrop:v3
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
        - |
          pip install --no-cache-dir jupyter
          cd /mnt/pvc/diss/Small-scale-RI-imaging-mrop
          exec jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
        ports:
        - containerPort: 8888
        resources:
          requests:
            cpu: 32
            memory: '32Gi'
          limits:
            cpu: 32
            memory: '32Gi'
            nvidia.com/gpu: 1
        volumeMounts:
          - mountPath: /mnt/pvc
            name: volume
          - mountPath: /mnt/shared
            name: volume2
          - mountPath: /dev/shm
            name: dshm
      imagePullSecrets:
        - name: eidfreg
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: s2908448-aspp-pvc
        - name: volume2
          persistentVolumeClaim:
            claimName: mlas-shared-pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3